#!/usr/bin/env ruby

$LOAD_PATH.unshift File.dirname(__FILE__) + '/lib'  #i hate you, rake
require 'secret_santa' 

people = []
puts 'Please enter the participants in the form FirstName LastName <eMailAddress>'
puts 'Enter a blank line when finished'
while true
  person_string = gets.chomp
  break unless person_string.match(/\w+/)
  people.push(Person.new(person_string))
end

s = SecretSanta.new(people)
puts 'Santas have been assigned as follows:'
p s.assign_santas
puts 'Now eMailing all participants...'
s.notify_santas
puts 'Done!'
